"""utenti sessioni ruoli permessi

Revision ID: cd1d08a4ce6a
Revises: 
Create Date: 2026-09-25 10:01:32.038086
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'cd1d08a4ce6a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('di_sistema', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('stato', sa.String(length=16), nullable=False),
    sa.Column('email_verificata_il', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('tentativi_falliti', sa.Integer(), nullable=False),
    sa.Column('bloccato_fino', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stato IN ('pending', 'active', 'suspended', 'deleted')", name='ck_users_stato'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email_trgm', 'users', ['email'], unique=False, postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.create_table('auth_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('esito', sa.String(length=16), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('dettagli', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quando', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("esito IN ('ok', 'ko')", name='ck_auth_events_esito'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_events_tipo_quando', 'auth_events', ['tipo', 'quando'], unique=False)
    op.create_index(op.f('ix_auth_events_user_id'), 'auth_events', ['user_id'], unique=False)
    op.create_table('email_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scade_il', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usato_il', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo IN ('verify', 'reset')", name='ck_email_tokens_tipo'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_tokens_user_tipo', 'email_tokens', ['user_id', 'tipo'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('creata_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vista_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scade_il', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocata_il', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assegnato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assegnato_da', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assegnato_da'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_index('ix_email_tokens_user_tipo', table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_index(op.f('ix_auth_events_user_id'), table_name='auth_events')
    op.drop_index('ix_auth_events_tipo_quando', table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_index('ix_users_email_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'email': 'gin_trgm_ops'})
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
